### ISSUE TITLE
[Checklist] Merge plans for PF handler and EnterUser

### ISSUE THREAD

**Issue by shrik3** [QuarkContainer/Quark#1066]
Hi @CharlyYu This is some notes regarding our current merge window:

**Plan**

- [x] 1. Merge #1027 : it would be nice if you resolve [this comment](https://github.com/QuarkContainer/Quark/pull/1027#discussion_r1420268223), but it's fine if you don't.
- [x] 2. Merge #1038 and #1042, these are self contained, should have no conflicts
- [x] 3. Review #1034 : this is the page fault handler. Note that this PR includes commits from #1027. Please **ping @chl337 to rebase** after step 2.  Then it can be merged.
- [x] 4. After all above I'll rebase and merge #1058. 

After these merges we should:
- have a working page fault handler
- be able to run hello-world image from docker, with or without CopyPageWithPF.

Still issues:
- (specific to our machine) the PAN is not handled correctly when accessing EL0 memory from EL1
- brk syscall is perhaps wrong (causing Exception class 0)

**Comment by CharlyYu** [comment]
> it would be nice if you resolve https://github.com/QuarkContainer/Quark/pull/1027#discussion_r1420268223, but it's fine if you don't.
The comment is resolved and #1027 is resolved

**Comment by CharlyYu** [comment]
#1042 is merged, but #1038 has unresolved comments, Do we have to resolve this first? @shrik3 @chl337  

https://github.com/QuarkContainer/Quark/pull/1038#discussion_r1451631370

**Comment by CharlyYu** [comment]
> update: with the updated PF handler (https://github.com/QuarkContainer/Quark/pull/1034) doesn't seem to work well with CopyPageUnsafe:

Does this problem still exists?

**Comment by shrik3** [comment]
> > update: with the updated PF handler (#1034) doesn't seem to work well with CopyPageUnsafe:
> 
> Does this problem still exists?

I forgot to update the comment, this has been resolved. Please ignore.

**Comment by chl337** [comment]
@CharlyYu @shrik3 I have rebased [#1034](https://github.com/QuarkContainer/Quark/pull/1034) against the [armdev-branch](https://github.com/QuarkContainer/Quark/commits/armdev/).

**Comment by chl337** [comment]
> #1042 is merged, but #1038 has unresolved comments, Do we have to resolve this first? @shrik3 @chl337
> 
> [#1038 (comment)](https://github.com/QuarkContainer/Quark/pull/1038#discussion_r1451631370)

@CharlyYu The issue is resolved.
@shrik3 @CharlyYu My suggestion would be to merge the PR and open a (low-priority) issue to replace the CopyPageUnsafe ([x86_64](https://github.com/QuarkContainer/Quark/blob/5b502bdac857cfdab0aa23f1f4b7eaac5be7d7b2/qlib/kernel/arch/x86_64/syscall_entry.s#L170), [aarch64](https://github.com/QuarkContainer/Quark/blob/cc75301ebc748735ddcafa25789ad0c29fc581cf/qlib/kernel/arch/aarch64/syscall_entry.s#L9)) with Rust native [copy_nonoverlapping](https://doc.rust-lang.org/nightly/core/ptr/fn.copy_nonoverlapping.html#).

**Comment by abel-von** [comment]
Is #1034 is ready to be merged? if so, please remove the WIP in the pr and I will merge it.

**Comment by chl337** [comment]
> Is #1034 is ready to be merged? if so, please remove the WIP in the pr and I will merge it.

@abel-von I will do some refactoring and ping you as soon as I am done.

**Comment by shrik3** [comment]
finished
